apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: examen-backend-despachos-hpa
  namespace: examen
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: examen-backend-despachos
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: examen-backend-ventas-hpa
  namespace: examen
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: examen-backend-ventas
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
