apiVersion: apps/v1
kind: Deployment
metadata:
  name: examen-frontend
  namespace: examen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: examen-frontend
  template:
    metadata:
      labels:
        app: examen-frontend
    spec:
      containers:
        - name: frontend
          image: {{ECR_URL}}/examen-frontend:eks-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
